# Generated by Django 5.1.3 on 2024-11-30 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_inspector_warehousecert'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsCompany',
            fields=[
                ('company_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('road', models.CharField(max_length=25)),
                ('area', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='PackedProduce',
            fields=[
                ('barcode', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('weight', models.FloatField()),
                ('material', models.CharField(max_length=100)),
                ('cost_per_unit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_plate_no', models.CharField(max_length=15, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('max_capacity', models.FloatField()),
                ('gps_tracking_number', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryofPacked',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('transport_date', models.DateField()),
                ('quantity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('cost', models.FloatField()),
                ('warehouseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.warehouse')),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.packedproduce')),
                ('vehicleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.vehicle')),
            ],
        ),
    ]
