# Generated by Django 5.1.3 on 2024-11-30 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_packingfacility_facilitycertification'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestedProduce',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('sowing_date', models.DateField()),
                ('harvest_date', models.DateField()),
                ('weight', models.FloatField()),
                ('smoothness', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('fungal_growth', models.BooleanField()),
                ('weather_conditions', models.CharField(max_length=255)),
                ('pesticides_used', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryHarvested',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('transport_date', models.DateField()),
                ('quantity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('cost', models.FloatField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.packingfacility')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.vehicle')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.harvestedproduce')),
            ],
        ),
    ]
