# Generated by Django 5.1.3 on 2024-12-01 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_harvestedproduce_deliveryharvested'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('registration_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('size', models.FloatField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentSpecialist',
            fields=[
                ('specialist_id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionSpecialist',
            fields=[
                ('NspecialistID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='logistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.logisticscompany')),
                ('vehicle_Num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fat_content', models.FloatField()),
                ('sugar_content', models.FloatField()),
                ('vitamin_content', models.FloatField()),
                ('mineral_content', models.FloatField()),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.packedproduce')),
                ('nutritionist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.nutritionspecialist')),
            ],
        ),
        migrations.CreateModel(
            name='Specialist_License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=255)),
                ('date_received', models.DateField()),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.governmentspecialist')),
            ],
        ),
        migrations.CreateModel(
            name='FarmProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.harvestedproduce')),
                ('registration_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.farm')),
            ],
            options={
                'unique_together': {('batchID', 'registration_id')},
            },
        ),
    ]
