# Generated by Django 5.1.3 on 2024-12-01 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_farm_governmentspecialist_nutritionspecialist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField()),
                ('date_expired', models.DateField()),
                ('ventilation', models.CharField(max_length=55)),
                ('cleanliness', models.CharField(max_length=55)),
            ],
        ),
        migrations.AddConstraint(
            model_name='nutritioncontentreport',
            constraint=models.UniqueConstraint(fields=('nutritionist_id', 'barcode'), name='unique_nutritionist_barcode'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='inspector_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.inspector'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='vehicle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.vehicle'),
        ),
        migrations.AddConstraint(
            model_name='inspectionreport',
            constraint=models.UniqueConstraint(fields=('inspector_id', 'vehicle_id', 'date_received'), name='unique_inspector_vehicle_date'),
        ),
    ]
