# Generated by Django 5.1.3 on 2024-12-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_inspectionreport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.CharField(max_length=155),
        ),
    ]
