# Generated by Django 5.1.3 on 2024-12-03 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_packingfacilitycert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('name', models.CharField(max_length=65, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='warehousedistribution',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='warehousedistribution',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='warehousedistribution',
            name='supname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='warehousedistribution',
            unique_together={('warehouseid', 'supname', 'date')},
        ),
        migrations.RemoveField(
            model_name='warehousedistribution',
            name='retailername',
        ),
    ]
